[theme]
primaryColor = "#1976D2"  # Deep blue (trust, clarity)
backgroundColor = "#E3F2FD"  # Very light blue (calm, gentle)
secondaryBackgroundColor = "#FFFFFF"  # White (clean, minimalist)
textColor = "#0D47A1"  # Dark blue (serious, readable)
font = "sans serif"

[client]
toolbarMode = "minimal"